### ISSUE TITLE
Trouble adding Spotify controls

### ISSUE THREAD

**Issue by jasontucker** [rmlewisuk/TouchBarWidgets#1]
Can you provide some detail into how you add the Spotify controls to Better Touch Tool? I don't know if I'm to use a Widget or a TouchBar button to add in the play prev and next buttons.

**Comment by rmlewisuk** [comment]
I actually stopped using these a while back so I can't help much I'm afraid. This might help: https://lucatnt.com/2017/02/display-the-currently-playing-track-in-itunesspotify-on-the-touch-bar/
